# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e757fe6a4ee7427c448fded287728f6c75fa23eae17fa4615e22d55c45297204da2d6b872390e92a45026cf350cd9869ee95aa8232edeef4f776a14a7786190


test:
  secret_key_base: e3742cca8c78155608630e8172161e5ba7318123b54c75188949fbe0ad1251d66f20c909768879e7f3e745000b0fb9da0d34fa8131f8d4e27e3ad04d2cf352b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
